#!/usr/bin/env python3
"""Generate index.html and staging.html from the files in articles/.

For each article the generator extracts:
  - the title   -> the first <h1>
  - the summary -> the first <p> whose class list contains "summary"
  - the date    -> the first <p class="meta"> (used for ordering)
  - published   -> presence of <meta name="status" content="published">

index.html   lists only published articles.
staging.html is a faithful copy of index.html that lists every article present,
             published or not.

The site has no build step for writing; this script is what the GitHub Pages
workflow runs to (re)build the two listing pages before deploying. Run it
locally the same way: `python3 scripts/build_index.py`.
"""

from __future__ import annotations

import html
from datetime import datetime
from html.parser import HTMLParser
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
ARTICLES_DIR = ROOT / "articles"


class ArticleParser(HTMLParser):
    """Pull the title, summary, date and published flag out of one article."""

    def __init__(self) -> None:
        super().__init__(convert_charrefs=True)
        self.title: str | None = None
        self.summary: str | None = None
        self.date: str | None = None
        self.published = False
        self._capture: str | None = None
        self._depth = 0
        self._buf: list[str] = []

    def handle_starttag(self, tag, attrs):
        attrs = dict(attrs)

        if (
            tag == "meta"
            and attrs.get("name") == "status"
            and attrs.get("content") == "published"
        ):
            self.published = True

        # While capturing an element's text, just track nesting depth so we
        # know which end tag closes the element we care about.
        if self._capture is not None:
            self._depth += 1
            return

        classes = (attrs.get("class") or "").split()
        if tag == "h1" and self.title is None:
            self._start_capture("title")
        elif tag == "p" and "summary" in classes and self.summary is None:
            self._start_capture("summary")
        elif tag == "p" and "meta" in classes and self.date is None:
            self._start_capture("date")

    def handle_endtag(self, tag):
        if self._capture is None:
            return
        if self._depth > 0:
            self._depth -= 1
            return
        text = " ".join("".join(self._buf).split())
        setattr(self, self._capture, text)
        self._capture = None

    def handle_data(self, data):
        if self._capture is not None:
            self._buf.append(data)

    def _start_capture(self, name: str) -> None:
        self._capture = name
        self._depth = 0
        self._buf = []


PAGE = """<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{title}</title>
  <meta name="description" content="{description}">
  <link rel="stylesheet" href="assets/style.css">
</head>
<body>
  <!-- Generated by scripts/build_index.py — do not edit by hand. -->
  <div class="wrap">
    <header class="site">
      <h1>Musings</h1>
      <p class="tagline">{tagline}</p>
    </header>

    <main>
      <ul class="index">
{items}
      </ul>
    </main>

    <footer class="site">
      <p>&copy; 2026 Cyrille Boucher. Built as a static site, published with GitHub Pages.</p>
    </footer>
  </div>
</body>
</html>
"""

ITEM = """        <li>
          <a class="title" href="{href}">{title}</a>
          <p class="summary">{summary}</p>
        </li>"""


def parse_date(text: str | None):
    if not text:
        return None
    try:
        return datetime.strptime(text, "%d %B %Y")
    except ValueError:
        return None


def collect():
    entries = []
    for path in sorted(ARTICLES_DIR.glob("*.html")):
        parser = ArticleParser()
        parser.feed(path.read_text(encoding="utf-8"))
        entries.append(
            {
                "href": f"articles/{path.name}",
                "title": parser.title or path.stem.replace("-", " ").title(),
                "summary": parser.summary or "",
                "date": parse_date(parser.date),
                "published": parser.published,
            }
        )
    # Most recent first; undated articles fall to the end but keep their order.
    entries.sort(key=lambda e: e["date"] or datetime.min, reverse=True)
    return entries


def render(entries, *, title, tagline, description):
    items = "\n".join(
        ITEM.format(
            href=html.escape(e["href"], quote=True),
            title=html.escape(e["title"]),
            summary=html.escape(e["summary"]),
        )
        for e in entries
    )
    return PAGE.format(
        title=html.escape(title),
        description=html.escape(description, quote=True),
        tagline=html.escape(tagline),
        items=items,
    )


def main() -> None:
    entries = collect()
    published = [e for e in entries if e["published"]]

    (ROOT / "index.html").write_text(
        render(
            published,
            title="Musings",
            tagline="Writings on various topics and subjects.",
            description="Writings on various topics and subjects.",
        ),
        encoding="utf-8",
    )
    (ROOT / "staging.html").write_text(
        render(
            entries,
            title="Musings — staging",
            tagline="Staging — every page, including drafts not yet published.",
            description="Staging index of all pages, including unpublished drafts.",
        ),
        encoding="utf-8",
    )

    print(f"Wrote index.html ({len(published)} published) "
          f"and staging.html ({len(entries)} total).")


if __name__ == "__main__":
    main()
